title: |md
  # CMD_REGISTER (REQUEST)
| {near: top-center}

grid-rows: 1
grid-columns: 6
grid-gap: 0

1: CMD_REGISTER (1)
2: Width (4)
3: Height (4)
4: Name (N * 1)
5: *Buffer*
6: CMD_END_OF_COMMAND (1)
