title: |md
  # CMD_REGISTER (RESPONSE)
| {near: top-center}

grid-rows: 14
grid-columns: 1
grid-gap: 0

CMD_REGISTER (1)
SUCCESS(1)
Id (4)
X (4)
Y (4)
Capacity (4)
t2 (8)
t3 (8)
CMD_FULL_SERVER_UPDATE (1)
ID+ (4)
X+ (4)
Y+ (4)
Name+ (N * 1)
CMD_END_OF_COMMAND (1)
